service: api-salary-prediction
frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.14
  memorySize: 1024
  timeout: 25
  iam:
    role: arn:aws:iam::${aws:accountId}:role/LabRole

functions:
  listar:
    handler: SalaryPrediction.lambda_handler
    events:
      - http:
          path: /predecir/sueldo
          method: post
          cors: true
          integration: lambda
